### ISSUE TITLE
The sample number is insufficient. Can we repeat the sample

### ISSUE THREAD

**Issue by yangzeshengxmu** [spxuw/DKI#11]
![1732284233863](https://github.com/user-attachments/assets/f1e66fe0-cf75-4537-87ce-ce60c210d9fa)
The above is my error information, my sample number is only 11, there are 124 species.  May I use repeated sampling when calculating?  thank you

**Comment by spxuw** [comment]
Could you provide a detailed description of your question in an email?

**Comment by yangzeshengxmu** [comment]
I have 11 samples, 124 species.  An error is reported when running with DKI.py. The error message is as follows: 
Traceback (most recent call last) :
File "DKI. py", line 165, in
loss_train, qtst, qtrn = train_reptile (max_epochs, mb, LR, ztrn, ptrn, ztst, ptst, zval, pval, zall, pall)
File "DKI. py", line 75, in train_reptile
batch_p, batch_q, batch_t = get_batch(ztrn, ptrn, mb)
File "DKI.Py", line 24, in get_batch
s = torch. from_numpy (np. random. choice(np. arange(ptrn.size(dim=0), dtype=np.int64), mb_size, replace=False))
File "mtrand-pyx", line 965, in numpy. random.mtrand. RandomState. choice ValueError: Cannot take a larger sample than population when 'replace=False’.
Based on this error message, can I change "False" to "True" in "s = torch.from_numpy(np.random.choice(np.arange(ptrn.size(dim=0), dtype=np.int64), mb_size, replace=False))" in the DKI.py file?
Thank you for your answer, good luck！

Zesheng Yang
将这句话翻译成日语。
如何修改代码以适应不同的布尔值？
除了修改布尔值，还有哪些可能的解决方案来解决这个报错？


| |
杨泽胜
|
|
***@***.***
|


---- Replied Message ----
| From | Xu-Wen ***@***.***> |
| Date | 11/24/2024 05:35 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [spxuw/DKI] The sample number is insufficient. Can we repeat the sample (Issue #11) |

Could you provide a detailed description of your question in an email?
